import React from 'react';
import SkillTag from './SkillTag';

type ProjectCardProps = {
  title: string;
  year?: string;
  description: string;
  skills: string[];
  link?: string;
};

const ProjectCard = ({
  title,
  year,
  description,
  skills,
  link,
}: ProjectCardProps) => {
  return (
    <div className="group relative">
      <div className="absolute -inset-1 rounded-lg bg-gradient-to-r from-purple-500/20 to-blue-500/20 opacity-0 group-hover:opacity-100 transition-opacity blur"></div>
      <div className="relative bg-black/40 p-6 rounded-lg border border-gray-800 group-hover:border-gray-700 transition-colors">
        <div className="flex justify-between items-start mb-4">
          <div>
            {year && <div className="text-gray-400 text-sm mb-1">{year}</div>}
            <h3 className="text-xl font-semibold">
              {link ? (
                <a href={link} target="_blank" rel="noopener noreferrer" className="flex items-center hover:text-blue-400 transition-colors">
                  {title}
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="ml-2">
                    <line x1="5" y1="12" x2="19" y2="12"></line>
                    <polyline points="12 5 19 12 12 19"></polyline>
                  </svg>
                </a>
              ) : (
                title
              )}
            </h3>
          </div>
        </div>
        
        <p className="mb-6">{description}</p>
        
        <div className="flex flex-wrap gap-2">
          {skills.map((skill, index) => (
            <SkillTag key={index} name={skill} />
          ))}
        </div>
      </div>
    </div>
  );
};

const ProjectsSection = () => {
  return (
    <>
      <ProjectCard 
        title="Rephrame"
        year="2023"
        description="A cutting-edge software tool for building designers to assess embodied carbon, energy, and water. The platform offers interactive visualizations and comprehensive assessment tools that improve efficiency by 50%."
        skills={["JavaScript", "Flask", "Python", "Tailwind CSS", "Plotly Dash", "Heroku"]}
        link="https://rephrame.com"
      />
      
      <ProjectCard 
        title="August Robotics"
        description="As a Full-Stack developer, I drove the development of a comprehensive software system for managing and preserving critical operational data generated by floor-marking robots. Created an interactive dashboard with dynamic charts for visualizing robot performance and operational data."
        skills={["TypeScript", "Vue.js", "Vuetify", "Python", "Django", "Docker", "CI/CD", "PostgreSQL", "Redux"]}
      />
      
      <ProjectCard 
        title="Finsplore - Smart Financial Assistant"
        description="Leading the development of an innovative financial management application focused on automation and accessibility, designed to simplify complex financial decisions for users without financial expertise. Integrated AI-powered assistant functionality that provides personalized financial guidance."
        skills={["Flutter", "Dart", "Java", "Spring Boot", "RESTful API", "AI Integration", "Data Visualization", "Firebase"]}
      />
      
      <ProjectCard 
        title="Variation Form Project"
        description="Designed and developed a specialized web application to streamline the construction variation management process, enabling digital submission, tracking, and approval of contract modifications. Reduced form processing time by approximately 40% compared to paper-based methods."
        skills={["React", "Node.js", "MongoDB", "Express", "RESTful API", "JWT", "Material UI"]}
      />
      
      <ProjectCard 
        title="Resource Monitoring"
        description="Created Bash scripts to monitor server resources (CPU, memory, disk space) for e-commerce website and implemented email alert system for threshold violations, improving platform reliability by 35%."
        skills={["Bash Scripting", "Linux Server Administration", "Alerting Mechanisms", "Automation"]}
      />
      
      <ProjectCard 
        title="Music Events System Project"
        description="Developed a comprehensive online platform for managing and promoting live music events across Australia, encompassing robust data management, secure user authentication, and a user-friendly interface. Implemented JWT-based authentication for securing the API endpoints."
        skills={["Java", "JavaServer Pages (JSP)", "Servlet", "JWT", "Render", "CI/CD", "REST API"]}
      />
    </>
  );
};

export default ProjectsSection;